spring.application.name=SpringProje

# MS SQL Server baglanti bilgileri
# Veritabani adini projenle uyumlu hale getir
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=KUTUPHANE_DB;encrypt=true;trustServerCertificate=true
spring.datasource.username=YOUR_DB_USERNAME
spring.datasource.password=YOUR_DB_PASSWORD
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate Ayarlari
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.jackson.time-zone=Europe/Istanbul

spring.sql.init.mode=always # projeyi ilk kez çalıştırırken always olarak kalsın. daha sonraki çalıştırmalarda never yapalım!

# Logging
logging.level.org.springframework.security=INFO
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=INFO